#!/usr/bin/env bash
# ds-dev PID 1 (under `init: true`, so detached sessions' orphans get reaped).
#
# Order matters and is not arbitrary:
#   ssh identity -> git -> pull -> venv -> sshd host key -> ssh env -> claude
#   state -> [rc(bg)] -> sshd(fg)
# The pull comes before the venv sync so the sync reads the lockfile the pull just
# brought in. Everything that could block on a prompt — every one of Claude's
# first-run dialogs — is settled before anything that could meet one starts,
# because nothing in here can answer one.
#
# **sshd is the FOREGROUND process, and that is the whole design.** This container
# is used by ssh-ing into it — from a PC, or from Termux on the phone — and
# running claude or the TUI inside an `abduco` session there. So the thing whose
# lifetime the container's lifetime should equal is the ssh endpoint.
#
# It was the other way round until now: the Claude Remote Control supervisor was
# exec'd as PID 1's payload so `docker logs` would show the Claude session, and
# sshd ran in the background under it. That made an optional, occasionally-wedging
# daemon the thing keeping the container alive — a bug in it, or an upstream
# change that makes remote-control exit hard, took the ssh door down with it. It
# is inverted now: remote control is opt-in (DS_REMOTE_CONTROL=1), runs in the
# background with a log of its own, and cannot affect PID 1 either way.
#
# `set -u` and NOT `set -e`. Under errexit, any one best-effort step failing —
# an offline `uv sync`, a `git config` on a read-only tree — kills PID 1 and the
# container with it, which is precisely the failure mode where you most want an
# ssh door to still open so you can look. Every step below either cannot fail or
# says what it could not do and carries on.
set -u

CFG="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
DEV_SSH=/workspace/.dev-ssh

say() { printf '[entrypoint] %s\n' "$*"; }

# ── ssh: the git identity, and pinned host keys ─────────────────────────────
# dossier's git identity is a key pair in the gitignored .dev-ssh/ inside the
# bind-mounted clone, generated by login.sh. It rides with the checkout rather
# than living in a secrets directory outside it (or3 needs one of those for a
# vessel-LAN key and a per-repo deploy key; there is nothing of that shape here).
mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
if [ -d "$DEV_SSH" ]; then
  chmod 600 "$DEV_SSH"/id_* 2>/dev/null || true
  [ -f "$DEV_SSH/config" ] && ln -sf "$DEV_SSH/config" "$HOME/.ssh/config"
  # Push over SSH with those keys WITHOUT editing the shared .git/config remote
  # (which would drag the host's clone onto SSH too, since it is the same file):
  # rewrite GitHub HTTPS->SSH in the container's own ~/.gitconfig only.
  git config --global url."git@github.com:".insteadOf "https://github.com/" || true
fi

# GitHub's host keys, written from scratch on every start. Ported from or3: a
# changed key then has to be an edit to THIS FILE, and can never be a
# first-contact `yes` typed by whoever happened to run the first `git pull` — or,
# worse, accepted silently by an `accept-new` in a generated ssh config. These
# are the keys GitHub publishes at https://api.github.com/meta (.ssh_keys).
cat > "$HOME/.ssh/known_hosts" <<'EOF'
github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
EOF
chmod 600 "$HOME/.ssh/known_hosts"

# authorized_keys is what lets anyone in at all — sshd reads it straight out of
# the read-only bind mount of the host user's .ssh directory (sshd_config's
# AuthorizedKeysFile), so there is no second key list to keep in step. Without it
# the container comes up fine and is simply unreachable, so say so loudly rather
# than letting that be discovered later as a mystery.
if [ ! -s "$HOME/.host-ssh/authorized_keys" ]; then
  say "WARNING: no authorized_keys under ~/.host-ssh — nothing can ssh in."
  say "         DEV_SSH_AUTHORIZED_KEYS in dev/.env must point at the HOST user's"
  say "         .ssh DIRECTORY, and that directory's authorized_keys must list the"
  say "         public key(s) that will connect. \`docker exec\` still works."
fi

# ── git ─────────────────────────────────────────────────────────────────────
# /workspace is owned by the host user; git refuses to operate on a repository it
# considers someone else's unless told. The uid is built to match, but a rebuild
# that changed it — or a clone moved between accounts — turns every git command
# in here into "detected dubious ownership" with no obvious cause.
git config --global --add safe.directory /workspace 2>/dev/null || true

# A commit identity, or every commit made in here dies on "Please tell me who you
# are". Passed through by compose.yaml's `environment:` block — a name in .env
# alone does NOT reach the container.
git config --global user.name  "${GIT_USER_NAME:-Gavin Fernandes}" || true
git config --global user.email "${GIT_USER_EMAIL:-gavinfernandes2012@pm.me}" || true

# ── the workspace ───────────────────────────────────────────────────────────
# Pull on start. --ff-only, and never fatal: a container that will not come up
# because the network is down, or because the tree has local work, is worse than
# one running a slightly old checkout — and /workspace is the HOST's clone, so a
# merge started here would leave the host's working tree half-done.
if [ -d /workspace/.git ]; then
  if git -C /workspace pull --ff-only 2>&1 | sed 's/^/[entrypoint] git: /'; then :; else
    say "pull skipped (not fast-forward, or offline) — the checkout is unchanged"
  fi
fi

# ── the Python satellite ────────────────────────────────────────────────────
# Deps are baked into /home/dev/venv at build time; add the editable project now
# that /workspace is mounted. Keep these flags in sync with the Dockerfile's build
# sync (--all-extras --group driver) or this call will UNINSTALL the baked extras.
# Best-effort so the container still comes up if the clone is absent or offline.
if [ -f /workspace/pyproject.toml ]; then
  uv sync --frozen --all-extras --group driver \
    || say "uv sync failed (offline, or the lock is out of step) — the baked venv is unchanged"
fi

# ── sshd host key ───────────────────────────────────────────────────────────
# Generated once into the persisted ds-ssh-host volume. A host key regenerated on
# every build would ask every client to accept a changed key on every rebuild,
# which trains you to wave one through — the one habit that makes the check
# worthless.
mkdir -p "$HOME/.ssh-host" && chmod 700 "$HOME/.ssh-host"
[ -f "$HOME/.ssh-host/ssh_host_ed25519_key" ] || \
  ssh-keygen -t ed25519 -f "$HOME/.ssh-host/ssh_host_ed25519_key" -N "" -C ds-dev >/dev/null

# ssh sessions do not inherit this process's environment, so publish it for sshd
# to read via PermitUserEnvironment — this is what puts the venv AND cargo on an
# ssh session's PATH, and what gives Zed's toolchain detection its VIRTUAL_ENV.
# One KEY=value per line, unquoted: that format takes no quoting, and shell noise
# in it makes sshd reject the whole file. $PATH is already correct — the image
# sets it — so it is copied rather than reassembled here.
{
  echo "PATH=$PATH"
  env | grep -vE '^(PATH|PWD|SHLVL|_|HOME|OLDPWD|HOSTNAME)='
} > "$HOME/.ssh/environment"
chmod 600 "$HOME/.ssh/environment"

# ── Claude first-run state ──────────────────────────────────────────────────
# A file left holding empty tokens is worse than no file: `claude auth status`
# reports loggedIn false either way, but the login flow can trip over the husk.
# (or3 learned this by copying a phone's credentials.json in — claude reached the
# auth server one second after starting and wrote the file back with zero-length
# tokens. An OAuth login belongs to the device that performed it; the durable
# answer is one interactive `make dev-login`, which persists in the ds-claude
# volume. This container never copies credentials in, but the husk check is worth
# keeping: a half-finished login flow leaves the same file.)
if [ -f "$CFG/.credentials.json" ] \
   && ! grep -q '"accessToken": *"[^"]' "$CFG/.credentials.json" 2>/dev/null; then
  rm -f "$CFG/.credentials.json"
  say "removed a blanked .credentials.json — run: make dev-login"
fi

# The first-run dialogs a headless container cannot answer. Each defaults to unset
# on a FRESH volume, and each blocks claude on a prompt with nobody there:
#   projects["/workspace"].hasTrustDialogAccepted — workspace trust. Without it
#       `remote-control --spawn worktree` aborts with "Workspace not trusted".
#       /workspace is not $HOME, so unlike home-directory trust this is persisted.
#   remoteDialogSeen — the one-time "Enable Remote Control? [y/N]" consent. When
#       falsy, remote-control opens a readline prompt on stdin; with no interactive
#       stdin the supervisor's daemon can never answer it and re-prompts on every
#       restart. Seeding it true skips the prompt outright.
#   theme, hasCompletedOnboarding — the first-run walkthrough.
# Seeded on EVERY start whether or not remote control is enabled, because an
# interactive `claude` started over ssh meets the same three of them. Merged
# idempotently into any existing config, before claude starts, while nothing else
# holds the file open.
mkdir -p "$CFG"
python3 - "$CFG/.claude.json" /workspace <<'PY' || say "could not pre-seed .claude.json"
import json, os, sys

path, project = sys.argv[1], sys.argv[2]
try:
    with open(path) as f:
        cfg = json.load(f)
    if not isinstance(cfg, dict):
        cfg = {}
except (FileNotFoundError, json.JSONDecodeError):
    cfg = {}

dirty = False
entry = cfg.setdefault("projects", {}).setdefault(project, {})
if entry.get("hasTrustDialogAccepted") is not True:
    entry["hasTrustDialogAccepted"] = True
    dirty = True
if not cfg.get("theme"):
    cfg["theme"] = "dark"
    dirty = True
if cfg.get("hasCompletedOnboarding") is not True:
    cfg["hasCompletedOnboarding"] = True
    dirty = True
if cfg.get("remoteDialogSeen") is not True:
    cfg["remoteDialogSeen"] = True
    dirty = True

if dirty:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(cfg, f, indent=2)
    os.replace(tmp, path)
    os.chmod(path, 0o600)
PY

# ── Claude Remote Control — OFF unless asked for ────────────────────────────
# `claude remote-control` makes this container drivable from claude.ai/code and
# the mobile app. It used to be started on every boot, as PID 1's payload; it is
# opt-in and backgrounded now. The default way in is an ssh session, and a daemon
# nobody is driving is a live claude with a permission classifier for company.
#
# Turn it on for a spell with DS_REMOTE_CONTROL=1 in dev/.env, then `make up` —
# the entrypoint reads it at start, so `make restart` will NOT pick up the change.
# The supervisor polls for a login rather than failing without one, so ordering it
# against `make dev-login` does not matter.
#
# setsid and fully detached from this process's stdio: its stdout is a TUI that
# repaints, and putting that in `docker logs` is what buried sshd's own lines
# under megabytes of cursor-control escapes before. It keeps its own filtered log.
# Nothing here is conditional on it succeeding — a supervisor that dies takes
# nothing with it, which is the point of the inversion.
if [ "${DS_REMOTE_CONTROL:-0}" = "1" ]; then
  setsid bash /home/dev/rc-supervisor.sh </dev/null >/dev/null 2>&1 &
  say "remote-control supervisor started (log: ~/.local/share/remote-control.log)"
fi
# No `else` branch on purpose: with remote control off, nothing about it appears
# in the startup path at all. `make status` is where you ask whether it is on.

# ── sshd, in the foreground ─────────────────────────────────────────────────
# The container's payload. exec, so sshd IS this process: signals from `docker
# stop` reach it directly and the container's lifetime is exactly the endpoint's.
# Nothing you type inside can end it — `exit` closes an ssh session, `/exit`
# closes a claude, and PID 1 has not moved.
#
# -D stops it daemonising: daemon(0,0) would point its stderr at /dev/null and
# throw away the -e log that `docker logs ds-dev` is now made of.
#
# Nothing beyond this line runs. A start-up failure is in the log ABOVE it, which
# is what `make boot-log` prints.
say "sshd on :2222 in the foreground — ssh in and work in an abduco session"
say "    ssh ds-dev                               a shell"
say "    ssh -t ds-dev abduco -A claude claude    a claude that survives the link"
exec /usr/sbin/sshd -D -e -f /home/dev/sshd_config
